# Dependencies
markdown:     kramdown
highlighter:  rouge


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               'Hyun 블로그'
tagline:             ''
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         'Hyun 블로그'
url:                 https://corecode.pe.kr
baseurl:             ''
paginate:            5
#plugins:             [jekyll-paginate]
plugins:
  - jekyll-paginate
disqus_shortname:    hyunblog
disqus_url:          https://corecode.pe.kr

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0


pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true
